[project]
name = "moop-architecture"
version = "0.1.0"
description = "Modular Object Oriented Programming Architecture for Robotics Applications in Python"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ruff>=0.8.3",
]
